version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    env_file: 
      - ./docker.env
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    env_file: 
      - ./docker.env
    ports:
      - "27018:27017"